version: '{build}'

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
    QMAKE: C:\Qt\5.9\msvc2017_64\bin\qmake.exe
    VCVARS_SCRIPT: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat"
    VCVARS_PLATFORM: amd64
  - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
    QMAKE: C:\Qt\5.9\msvc2015\bin\qmake.exe
    VCVARS_SCRIPT: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat"
    VCVARS_PLATFORM: x86

init:
  - cmd: |
      "%VCVARS_SCRIPT%" %VCVARS_PLATFORM%
      %QMAKE% --version

build_script:
- cmd: |
    %QMAKE%
    nmake /nologo release
    cd quackleio
    %QMAKE%
    nmake /nologo release
    cd ../quacker
    %QMAKE%
    nmake /nologo release
